const IPC_MESSAGE = {
    GET_LIST_PRODUCTS: 'GET_LIST_PRODUCTS',
    GET_LIST_PRODUCTS_REPLY: 'GET_LIST_PRODUCTS_REPLY',
    GET_CART_ITEMS: 'GET_CART_ITEMS',
    GET_CART_ITEMS_REPLY: 'GET_CART_ITEMS_REPLY',
    GET_LIST_CATEGORIES: 'GET_LIST_CATEGORIES',
    GET_LIST_CATEGORIES_REPLY: 'GET_LIST_CATEGORIES_REPLY',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
    CREATE_MODAL: 'CREATE_MODAL',
    NOTIFICATION_MODEL_SHOW: 'NOTIFICATION_MODEL_SHOW',
    UPDATE_PURCHASE_STATUS: 'UPDATE_PURCHASE_STATUS',
    FILTER_PRODUCT_CATEGORY: 'FILTER_PRODUCT_CATEGORY',
    FILTER_PRODUCT_CATEGORY_REPLY: 'FILTER_PRODUCT_CATEGORY_REPLY',
    WINDOW_ACTION_TRACK: 'WINDOW_ACTION_TRACK',
    GET_PAYMENT_METHODS: 'GET_PAYMENT_METHODS',
    GET_PAYMENT_METHODS_REPLY: 'GET_PAYMENT_METHODS_REPLY',
};

export { IPC_MESSAGE };
